### ISSUE TITLE
Merge drainpipe-dev into drainpipe or drainpipe-src repository

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#187]
We would create a new separate project like `drainpipe-src` that does a subtree split to push into drainpipe and drainpipe-dev. This would be so packagist.org gets the projects as separate projects.

## Benefits

- When we make changes to either set of code, we can test them together. For example, if a change in drainpipe-dev affects drainpipe.
- We can synchronize the version numbers for both projects.
- One place to point people to for issues and bugs.

## Tasks

- [ ] Create a new repository to host the combined project.
- [ ] Create a github action to do the subtree splits and pushes
- [ ] Migrate issues
- [ ] Lock or turn off issues
- [ ] Update the readme's to point to the parent repository
- [ ] Reconcile that the two packages are currently on different major versions

**Comment by justafish** [comment]
This repository now splits out the `drainpipe-dev` subfolder and pushes it to https://github.com/Lullabot/drainpipe-dev on the `main` branch and tags
