### ISSUE TITLE
Document an end-to-end testing plan

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#188]
- [x] Testing Pantheon deployments (multidev in particular)
- [ ] A PR check that tests the GitHub actions themselves in a separate project
- [ ] Ensuring GitLab is working since we don't have active projects on it? Or deprecate?

**Comment by deviantintegral** [comment]
@mrdavidburns @YesCT anything to add as far as testing Drainpipe itself you would like to see?

**Comment by deviantintegral** [comment]
I've marked this as high because it will enable more contributors to work on the project.

**Comment by justafish** [comment]
I run this a lot locally which is useful https://github.com/Lullabot/drainpipe/blob/main/tests/local-test.sh

**Comment by davereid** [comment]
> I run this a lot locally which is useful https://github.com/Lullabot/drainpipe/blob/main/tests/local-test.sh

I ran into an error trying to use that test script:
```
+ cd drainpipe-test
+ cp -R ../drainpipe .
cp: cannot stat '../drainpipe': No such file or directory
```

I ran this from my drainpipe-named directory which is on the main branch of the Git repository. It possibly needs to be a double back directory like `../../drainpipe` but when I update it to that I also get the following:

```
+ cp -R ../../drainpipe .
cp: cannot copy a directory, '../../drainpipe', into itself, './drainpipe'
```

**Comment by rabbitlair** [comment]
Implementation of our release guidelines (including automated tests) can be seen in this release pull request: https://github.com/Lullabot/drainpipe/pull/1021
